### ISSUE TITLE
[BUG] Reference to files

### ISSUE THREAD

**Issue by taktakpeops** [MikeSouza/serverless-associate-waf#15]
Hi,

While using your plugin, we noticed that it doesn't handle `${file(./path)}`.

Our manifest look like that:

```
custom: ${file(./env.yml)}
```

In `env.yml`, we have the following:

```
associateWaf:
    name: regionalWaf
```

By doing some debugging in your plugin, we noticed that `this.serverless.service.custom` was having the raw value specified in the manifest. Therefore, the `config` object of the plugin never gets set to anything else than `undefined` + the plugin doesn't throw any exception.

For now, we "fixed" the issue by writing the following in our manifest:
```
custom: 
  env: ${file(./env.yml)}
  associateWaf:
    name: regionalWaf
```

But it obliges us to replace all `${custom.value}` expressions by `${custom.env.value}`.

Is it something that you are planning to support?

**Comment by MikeSouza** [comment]
No. This is likely not going to be supported since this is beyond the plugin's control. This is limitation is part of Serverless itself. You will notice that if you try doing what you're attempting to do with `${file(./path)}` for other top-level serverless yaml properties, such as `resources`, you're going to have a tough time as well.
